/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.2/userguide/building_java_projects.html in the Gradle documentation.
 */
import org.gradle.api.tasks.Copy
import org.gradle.api.file.DuplicatesStrategy

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application

    //TP
    id("com.christophecvb.touchportal.plugin-packager") version "9.0.0+"
    //TP dependencies
    //kotlin("jvm") version "1.9.0-RC"
    //kotlin("kapt") version "1.9.0-RC"
    id("java")
    id("com.github.gmazzo.buildconfig") version "3.1.0"
}

val versionMajor = 1
val versionMinor = 0
val versionPatch = 0

//val mainClassSimpleName = "Porta"
val mainClassPackage = "caffeineportal"

group = mainClassPackage
//tpPlugin.mainClassSimpleName = mainClassSimpleName
tpPlugin.mainClassSimpleName.set("Porta")


buildConfig {
    //packageName = "${project.group}"
    packageName("caffeineportal")

    //useKotlinOutput()
    useJavaOutput()

    buildConfigField("String", "NAME", "\"${project.name}\"")
    buildConfigField("String", "VERSION_NAME", "\"$version\"")
    buildConfigField("long", "VERSION_CODE", "${versionMajor * 1000 + versionMinor * 100 + versionPatch}")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()

    //jitpack for git
    maven(url = "https://jitpack.io")

    //TP snapshot for 9.0.0
    maven(url = "https://s01.oss.sonatype.org/content/repositories/snapshots/")
}

dependencies {
    // Use JUnit test framework.
    testImplementation("junit:junit:4.13.2")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:31.1-jre")

    //casterlabs
    implementation("co.casterlabs.Casterlabs:PluginSDK:8383849")

    //TP
    implementation("com.christophecvb.touchportal:plugin-sdk:9.0.0+")
    annotationProcessor("com.christophecvb.touchportal:plugin-sdk-annotations-processor:9.0.0+")
    //TP dependency
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    //implementation("com.christophecvb.touchportal.plugin-packager:Library:8.2.1") //not found!!
    //kapt("com.christophecvb.touchportal.plugin-packager:AnnotationsProcessor:8.2.1")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

application {
    // Define the main class for the application.
    mainClass.set("caffeineportal.App")
}

//replacing jar with fatJar
tasks.named("jar") {
    enabled = false
}
// tasks.named<Copy>("copyJar") {
//     duplicatesStrategy = DuplicatesStrategy.EXCLUDE
// }
tasks.named("build") {
    dependsOn("fatJar")
}
tasks.named("distZip") {
    //dependsOn("fatJar")
    enabled = false
}
tasks.named("distTar") {
    //dependsOn("fatJar")
    enabled = false
}
tasks.named("startScripts") {
    //dependsOn("fatJar")
    enabled = false
}

tasks.create("fatJar", Jar::class) {
    group = "build"
    description = "Creates a self-contained fat JAR of the application that can be run."
    manifest.attributes["Main-Class"] = "caffeineportal.App"
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    val dependencies = configurations
        .runtimeClasspath
        .get()
        .filter { file ->
            val dependency = file.toString()
            !dependency.contains("co.casterlabs")
        }
        .map(::zipTree)

    from(dependencies)
    with(tasks.jar.get())
}