/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package caffeineportal;

public class App {
    // TODO refactor com.ayrlin.caffeineportal
    // TODO figure out jarring reqs.

    // should have just came from caffein onInit
    public static void init() {
        System.out.println("CaffeinePortal Main Application system out~");
        Porta.start("start");

    }

}
