/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package caffeineportal;

import xyz.e3ndr.fastloggingframework.logging.FastLogger;
import xyz.e3ndr.fastloggingframework.logging.LogLevel;

public class App {
    public static void main(String[] args) {
        System.out.println("CaffeinePortal Main Application system out~");
        FastLogger.logStatic(LogLevel.DEBUG, "CaffeinePortal Main Application checking in with the CasterLabs side~");

        // should have just came from caffein onInit
    }
}
